### ISSUE TITLE
Update Etherscan Token Info 

### ISSUE THREAD

**Issue by Kaust1k** [tessr-labs/social#5]
Update Token Info (Website, logo, etc.)

- this is required to upgrade TSRX from “Unknown” Reputation to “Neutral” Reputation

- next step will be moving to “Okay” Reputation after more stringent verification

**Comment by tessr8** [comment]
DONE and DONE 

     1.
    Sign message
     2.
    Verify signed message
    3.
    Fill in form

Thank you for your submission.

You will receive an email containing further instructions shortly.

Our usual processing is 3 business days; please do not submit duplicate submission within this period of time.

Thank you once again for your patience.
